### PR TITLE
[FIX] New core/inventory functions added. (CHECK BOTTOM OF THE README)

### PR DESCRIPTION
**Pull request by Randolio**
Went through and manually replaced/added the new functions/exports with the recent qb-core changes.

I TESTED:
TRUNKS/STASHES/GLOVEBOXES, DROPPING, CRAFTING, WEAPONS, ADDING/REMOVING/USING ITEMS.

ONE SMALL ISSUE IS WEAPON ATTACHMENTS NOT BEING SHOWN IN THE UI TO REMOVE THEM FROM THE GUN. (I'M NOT GOOD WITH HTML SO) Maybe someone can contribute to this part?

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open for the same update/change?
* [x] Have you built and tested the `resource` in-game after the relevant change?

### CODE REVIEW

**Comment by vosscat** [comment]
just tested on fresh installed qb base server. it gave errors on SetInventory/LoadInventory/SaveInventory exports

**Comment by SKITTLE6969** [comment]
> just tested on fresh installed qb base server. it gave errors on SetInventory/LoadInventory/SaveInventory exports

did you follow the read me?

# Latest QB-CORE UPDATE (PLEASE READ)

MAKE SURE YOUR FOLLOWING RESOURCES ARE UP TO DATE:

QB-CORE
QB-SMALLRESOURCES
QB-WEAPONS

ONCE THAT IS DONE, YOU NEED TO REPLACE THE NEWLY ADDED EXPORTS IN QB-CORE.

FOR ME, ALL I HAD TO DO WAS MASS SEARCH MY RESOURCES FOLDER IN VISUAL STUDIO CODE LOOKING FOR 'qb-inventory' and replace it with 'lj-inventory'. 
SEE IMAGE LINK BELOW, FOLLOW IT EXACTLY.

(https://i.imgur.com/SyQwuoy.png)

I TESTED TRUNKS, STASHES, GLOVEBOXES, DROPPING, CRAFTING, WEAPONS, ADDING/REMOVING/USING ITEMS.

ONE SMALL ISSUE IS WEAPON ATTACHMENTS NOT BEING SHOWN IN THE UI TO REMOVE THEM FROM THE GUN. (I'M NOT GOOD WITH HTML SO)

**Comment by vosscat** [comment]
Ok just did another reinstall and it worked this time. Something might be wrong last time. After all its a problem on my side. Thanks.

**Comment by Randolio** [comment]
Good to hear :)

**Comment by SKITTLE6969** [comment]
> Good to hear :)

there were couple of new inventory updates today as well try to add them and see if anything improves :D

**Comment by UnitedLifeRP** [comment]
Installed it 3 times on 3 fresh installs and still not working, Once you open it and try close it you get froze on a blury screen. Errors in console: 

 Error loading script client/main.lua in resource qb-inventory: @qb-inventory/client/main.lua:1034: No such export AddTargetModel in resource qb-target

**Comment by NotReloads** [comment]
> Installed it 3 times on 3 fresh installs and still not working, Once you open it and try close it you get froze on a blury screen. Errors in console:
> 
> Error loading script client/main.lua in resource qb-inventory: @qb-inventory/client/main.lua:1034: No such export AddTargetModel in resource qb-target

Are you using qb-target? is your target system called qb-target or renamed? is it started? did you restart anything?
Eitherway, first step i would do is check if its renamed in javascript, whilst it should be called lj-inventory, you have it as qb-inventory.

**Comment by Randolio** [comment]
> 

Your error is in qb-inventory.. this is for lj-inventory..

**Comment by Beoriginalpt** [comment]
i got it to work once i updated to the latest qb-core but i lose all my inventory on disconnect. Any advice to solve that?

**Comment by Beoriginalpt** [comment]
so is not entering the inventory data on the mysql since the row "inventory" never changes from null i wonder what is wrong [mysql screenshoot](https://imgur.com/a/jEzIJNv)

**Pull request merged**
