### PR TITLE
fix: Update Inventory to support current QBCore

### PR DESCRIPTION
**Pull request by ihyajb**
**Pull Request Description**

When QBCore updated it broke the inventory, this PR fixes the errors caused by this while still keeping the look and features of lj-inventory

_Please include a general description of the changes made, why they were necessary, 
and any other general things to note._

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open for the same update/change?
* [x] Have you built and tested the `resource` in-game after the relevant change?
^^ Not Personally but `◥▶DEVIL X RAMBO◥▶#7907` from discord did

### CODE REVIEW

**Comment by SKITTLE6969** [comment]
reloading doesn't seem to work 
image

**Comment by kasumusic** [comment]
Also having issues with inventory items not saving as well as consumables not working.

**Comment by ihyajb** [comment]
yeah now with the "new new" core update, ill need to make another PR

**Comment by purplecofe** [comment]
> yeah now with the "new new" core update, ill need to make another PR

Hi, thank your contribution, any update for reoload issue fix?

**Comment by SKITTLE6969** [comment]
> yeah now with the "new new" core update, ill need to make another PR

Thanks AJ you're the best 🤠

**Comment by AnishBplayz** [comment]
did u just copy paste the qb-inventory....?

**Comment by GabbarFramework** [comment]
> yeah now with the "new new" core update, ill need to make another PR

Did U Fixed It

**Comment by J2W1905** [comment]
Im having issues with adding anything any items from a job, i cant eat or drink, i also cant put attachments on my guns or put ammo in them but it works fine with qb-inventory

**Comment by aprhoona** [comment]
there are errors in the inventory the elements are not saved since they updated qb-core 5 days ago

**Comment by ihyajb** [comment]
Outdated - PR Closed

**Pull request closed without merging**
